CREATE TABLE RolePermission (
	RolePermissionId UNIQUEIDENTIFIER PRIMARY KEY CONSTRAINT PK_RolePermission_RolePermissionId DEFAULT NEWID(),
    UsersGroupId UNIQUEIDENTIFIER NOT NULL,
	UsersGroupName NVARCHAR(100) NOT NULL,
    APIsId UNIQUEIDENTIFIER NOT NULL,
	APIsDescription NVARCHAR(100) NOT NULL,
    isAccess BIT NOT NULL DEFAULT 0,
	CreateBy UNIQUEIDENTIFIER NOT NULL,
    CreateTime DATETIME,
    UpdateBy UNIQUEIDENTIFIER NOT NULL,
    UpdateTime DATETIME NOT NULL
);